//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BET_PRO_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestOdd
    {
        public int id { get; set; }
        public Nullable<int> providerId { get; set; }
        public string value { get; set; }
        public string link { get; set; }
    }
}
