//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BET_PRO_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BET_PROEntities1 : DbContext
    {
        public BET_PROEntities1()
            : base("name=BET_PROEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BestOdd> BestOdds { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Odd> Odds { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<SifarnikIgara> SifarnikIgaras { get; set; }
        public virtual DbSet<Timovi> Timovis { get; set; }
        public virtual DbSet<Kladionice> Kladionices { get; set; }
    }
}
