//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BET_PRO_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int id { get; set; }
        public string abbreviation { get; set; }
        public string title { get; set; }
        public string default_match_type { get; set; }
        public string color { get; set; }
        public string updated_at { get; set; }
        public string created_at { get; set; }
    }
}
