//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BET_PRO_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int id { get; set; }
        public string url { get; set; }
        public string thumbnail { get; set; }
        public string fallback { get; set; }
        public string entity_type { get; set; }
        public Nullable<int> entity_id { get; set; }
        public string updated_at { get; set; }
        public string created_at { get; set; }
    }
}
