//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BET_PRO_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public long id { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public Nullable<long> gameId { get; set; }
        public string lifecycle { get; set; }
        public string turnamentId { get; set; }
        public string title { get; set; }
    }
}
