//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BET_PRO_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odd
    {
        public Nullable<long> matchId { get; set; }
        public Nullable<int> teamId { get; set; }
        public string name { get; set; }
        public Nullable<int> providerId { get; set; }
        public string link { get; set; }
        public int id { get; set; }
        public string kvota1 { get; set; }
        public string kvota2 { get; set; }
        public string procenat { get; set; }
    }
}
