//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BET_PRO_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int id { get; set; }
        public Nullable<long> matchId { get; set; }
        public Nullable<long> teamId { get; set; }
        public string name { get; set; }
        public string image { get; set; }
    }
}
